.TH DSNIFF 8 "10 December 2025" "2.5" "Dsniff man page"
.ad
.fi
.SH NAME
dsniff
\-
password sniffer
.SH SYNOPSIS
.na
.nf
.fi
\fBdsniff\fR [\fB-v\fR] [\fB-c\fR] [\fB-a\fR] [\fB-d\fR] [\fB-m\fR] [\fB-D\fR] [\fB-N\fR] [\fB-P\fR] [\fB-i
\fIinterface\fR | \fB-p \fIpcapfile\fR] [\fB-s \fIsnaplen\fR] [\fB-M \fImagics\fR] [\fB-f \fIservices\fR]
[\fB-t \fItrigger[,...]\fR]
[\fIexpression\fR]
.SH DESCRIPTION
.ad
.fi
\fBdsniff\fR is a password sniffer that handles FTP, Telnet, SMTP, HTTP, HTTPS,
POP, poppass, NNTP, IMAP, SNMP, LDAP, Rlogin, RIP, OSPF, PPTP,
MS-CHAP, NFS, VRRP, YP/NIS, SOCKS, X11, CVS, IRC,
PostgreSQL, Meeting Maker, Citrix ICA, Microsoft SMB, Oracle SQL*Net, Sybase, and Microsoft SQL
protocols.
.LP
\fBdsniff\fR automatically detects and minimally parses each
application protocol, saving only the interesting bits, logging only unique
authentication attempts. Full TCP/IP reassembly is provided by
libnids(3).
.LP
I wrote \fBdsniff\fR with honest intentions—to audit my own network
and to demonstrate the insecurity of cleartext network protocols.
Please do not abuse this software.
.SH OPTIONS
.IP \fB-c\fR
Perform half-duplex TCP stream reassembly to handle asymmetrically
routed traffic (such as when using arpspoof(8) to intercept client
traffic bound for the local gateway).
.IP \fB-v\fR
Verbose mode. Show banners.
.IP \fB-a\fR
Show all results. Otherwise, dsniff attempts to suppress duplicate entries.
.IP \fB-d\fR
Enable debugging mode.
.IP \fB-m\fR
Force protocol detection/DPI on known services. For example, \fB-m\fR will detect both SSH and HTTPS on port 443.
.IP \fB-N\fR
Resolve IP addresses to hostnames.
.IP \fB-P\fR
Enable promiscuous mode.
.IP \fB-C\fR
Force color output even if output is not a tty.
.IP \fB-D\fR
Disable DPI. Only decode known services (DPI is enabled by default on unknown ports).
.IP "\fB-i \fIinterface\fR"
Specify the interface to listen on.
.IP "\fB-p \fIpcapfile\fR"
Process the given PCAP capture file instead of packets observed on the network.
.IP "\fB-s \fIsnaplen\fR"
Analyze at most the first \fIsnaplen\fR bytes of each TCP connection,
rather than the default of 1024.
.IP "\fB-f \fIservices\fR"
Load triggers from a \fIservices\fR file. The default is to use the built-in list.
.IP "\fB-M \fImagicfile\fR"
Load magic signatures from a file. The default is to use the built-in list. Cannot be used with \fB-t\fR. Deep Packet Inspection (DPI) is based on Unix magic files. This feature can be used to selectively enable DPI. For example, to capture SSH banners on any port, use:
.RS
dsniff -M <(echo "0 string SSH-2.0- ssh")
.RE
.IP "\fB-t \fItrigger\fR[,...]"
Load triggers from a comma-separated list, specified as
\fIport\fR/\fIproto\fR=\fIservice\fR (e.g., 80/tcp=http). Triggers set default decoders for well-known services. The default is to use the built-in list.
.IP "\fIexpression\fR"
Specify a tcpdump(8) filter expression to select traffic to sniff.
.LP
On a SIGHUP signal, \fBdsniff\fR will dump its current trigger table to
\fIdsniff.services\fR.
.SH ENVIRONMENT
The following environment variable can be set:
.LP
.B ENV_ARGS
A string of command-line options. Using this variable hides the options from the process list:
.RS
# ENV_ARGS="-i eth0 -v" ./dsniff
.RE
.SH "SEE ALSO"
arpspoof(8), libnids(3), services(5), magic(5)
.SH AUTHOR
.na
.nf
Dug Song <dugsong@monkey.org>
Skyper <skyper@thc.org>
.SH HISTORY
\fBdsniff\fR was written by Dug Song in 2000. It is currently maintained by
The Hacker's Choice (https://thc.org). It is available at https://github.com/hackerschoice/dsniff.
.SH BUGS
\fBdsniff\fR's automatic protocol detection feature is based on the
classic file(1) command by Ian Darwin and shares its historical
limitations and bugs.
